- name: Create ticket repository
  hosts: localhost
  vars:
    data:
      serviceDeskId: 83
      requestTypeId: 2129
      requestFieldValues:
        customfield_13202:
          value: "{{ action }}"
        customfield_13356: "{{ repo_name }}"
        customfield_13942:
          value: "{{ bitbucket_project }}"
        customfield_13971:
          value: "{{ branching_model }}"
        customfield_14103:
          value: "{{ owner_team }}"
        customfield_13970:
          value: "{{ belongs_to_ms }}"
        customfield_13383:
          accountId: "{{ accountId }}"
        description: "{{ description }}"
      raiseOnBehalfOf: "{{ accountId }}"
    tasks:
    - name: Make ticket
      ansible.builtin.uri:
        url: "{{ url }}"
        user: "{{ username }}"
        password: "{{ password }}"
        method: POST
        body: "{{ data | to_json }}"
        status_code: 201
        force_basic_auth: yes
        headers:
          Content-Type: application/json
        register: result
    - name: Get response
      ansible.builtin.debug:
        var: result
