- name: create repo
  hosts: localhost
  vars:
        json_data:
                serviceDeskId: 83
                requestTypeId: 2129
                requestFieldValues:
                        customerfield_13202:
                                value: "Alta"
                        customerfield_13942:
                                value: "RappiCore"
                        customfield_13356: "test with ansible"
                        customfield_13971:
                                value: "GitFlow"
                        customfield_14103:
                                value: "core-services"
                        customfield_13970:
                                value: "Si"
                        description: "test for create ticket with ansible"
                        customfield_13383:
                                accountId: "628d53199c617b006a6d5596"

  tasks:
          - name: creation repository
            ansible.builtin.uri:
                    url: https://rappidev.atlassian.net/rest/servicedeskapi/request/
                    method: POST
                    body: "{{json_data|to_json}}"
                    status_code: 201
                    headers:
                            Accept: "application/json"
                            Authorization: Basic <token>
                            Content-type: application/json
            register: result
          - name: get response
            ansible.builtin.debug:
                    var: result.json
